In [2]:
class father:
    def __init__(self,property):
        self.property = property
    def func(self):
        print("father's func")

In [ ]:
class son(father):
    pass
son(1).func()

father's func


In [5]:
class son(father):
    def __init__(self,property):
        self.func=super().func
son(1).func()

father's func


In [5]:
class mother:
    def __init__(self):
        self.property = 1

In [ ]:
class son():
    def func(self):
        print(mother.property)

son().func()

AttributeError: type object 'mother' has no attribute 'property'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 5
      2     def func(self):
      3         print(mother.property)
----> 5 son().func()

Cell In[9], line 3
      2 def func(self):
----> 3     print(mother.property)

AttributeError: type object 'mother' has no attribute 'property'

In [1]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix[0][0]+matrix[1][1]+matrix[2][2]

15

In [15]:
tensor = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
tensor[0][:][0]+tensor[1][:][1]+tensor[2][:][2]
tensor[0][0]
persudo_contraction=[[_[i] for _ in tensor[i]]for i in range(3)]
print(persudo_contraction)
def degenrate(tensor,index):
    result=0
    for i in tensor:
        result+=i[index]
    return result
degenrate(persudo_contraction,0)
    

[[1, 4, 7], [11, 14, 17], [21, 24, 27]]


33

In [ ]:
#实现一个tensor的伪缩并（diagonal）

In [ ]:
#为了实现degenerate
def flip(tensor,index):
    result=0
    for i in tensor:
        result+=i[index]
    return result

def elementwise(func):
    pass

In [1]:
1+True

2

In [2]:
if 2:
    print(1)

1


In [ ]:
from sympy import symbols
from sympy.tensor.tensor import TensorIndexType, TensorIndex, TensorHead, tensor_indices
Lorentz = TensorIndexType('Lorentz', dummy_name='L')

A = TensorHead('A', [Lorentz])
B = TensorHead('B', [Lorentz])
mu = TensorIndex('mu', Lorentz, is_up=False)

# 定义 A 和 B 的分量（假设 4 维空间）
A0, A1, A2, A3 = symbols('A0 A1 A2 A3')  # A 的分量
B0, B1, B2, B3 = symbols('B0 B1 B2 B3')  # B 的分量

# 定义替换规则，将 A(mu) 和 B(-mu) 替换为具体分量
repl = {
    A(mu): [A0, A1, A2, A3],
    B(mu): [B0, B1, B2, B3]
}

# 由于 SymPy 不会自动处理哑指标求和，我们需要手动展开求和
# 假设内积是 A^mu * B_mu = sum(A[i] * B[i]) （欧几里得空间）
inner_product_value = sum(repl[A(mu)][i] * repl[B(mu)][i] for i in range(4))
print(inner_product_value)


KeyError: B(-mu)

In [8]:
from sympy import symbols, Matrix
from sympy.tensor.tensor import TensorIndexType, TensorIndex, TensorHead, tensor_indices

# 定义符号和指标
Lorentz = TensorIndexType('Lorentz', dummy_name='L')
i0, i1 = tensor_indices('i0 i1', Lorentz)
Ex, Ey, Ez, Bx, By, Bz, c = symbols('E_x E_y E_z B_x B_y B_z c')

# 定义电磁场张量 F
F = TensorHead('F', [Lorentz, Lorentz])

# 定义符号表达式替换规则
repl_symbolic = {
    F(-i0, -i1): Matrix([
        [0, Ex/c, Ey/c, Ez/c],
        [-Ex/c, 0, -Bz, By],
        [-Ey/c, Bz, 0, -Bx],
        [-Ez/c, -By, Bx, 0]
    ])
}

# 定义具体数值替换规则
repl_numeric = {
    Ex: 1.0,  # 电场x分量 = 1 V/m
    Ey: 0.5,  # 电场y分量 = 0.5 V/m
    Ez: 0.2,  # 电场z分量 = 0.2 V/m
    Bx: 0.1,  # 磁场x分量 = 0.1 T
    By: 0.3,  # 磁场y分量 = 0.3 T
    Bz: 0.05, # 磁场z分量 = 0.05 T
    c: 3e8    # 光速 = 3×10^8 m/s
}

# 创建一个张量表达式
expr = F(-i0, -i1)

# 分步替换：
# 1. 先用符号规则替换张量结构
expr_symbolic = expr.subs(repl_symbolic)
# 2. 再用数值规则替换具体值
expr_numeric = expr_symbolic.subs(repl_numeric)

# 或者一步完成替换
expr_final = expr.subs(repl_symbolic).subs(repl_numeric)

# 结果会是一个包含具体数值的矩阵
print(expr_final)


Matrix([[0, 3.33333333333333e-9, 1.66666666666667e-9, 6.66666666666667e-10], [-3.33333333333333e-9, 0, -0.0500000000000000, 0.300000000000000], [-1.66666666666667e-9, 0.0500000000000000, 0, -0.100000000000000], [-6.66666666666667e-10, -0.300000000000000, 0.100000000000000, 0]])


In [5]:
class VectorSpace:
    def __init__(self,dim:int,metric:list[int]|str="euclidean",is_dual:bool=False):
        self.dim = dim
        self.metric = metric
        self.is_dual = is_dual

    def __len__(self):
        return self.dim

    def __neg__(self):
        return VectorSpace(self.dim,self.metric,not self.is_dual)
    
    def __str__(self):
        return f"VectorSpace(dim={self.dim})"
    
class GeneralTensor:
    def __init__(self,dims:list,value:list=None,indices:list[VectorSpace]=None):
        self.dims = dims
        self.value = value
        self.indices = indices
    
    def __str__(self):
        return f"GeneralTensor(dims={self.dims}, value={self.value})"
    
    def __len__(self):
        return len(self.dims)
    
    def __getitem__(self, index):
        return self.value[index]
    
    def __call__(self, indices:list[VectorSpace]):
        self.indices = indices

mu=VectorSpace(2)
nu=VectorSpace(2)
G1=GeneralTensor([1],indices=[mu])
G2=GeneralTensor([1],indices=[mu])
a=G1.indices[0]
a is G2.indices[0]

True

In [13]:
dims = [2, 2, 4]
indices=[VectorSpace(dim) for dim in dims]
indices[0] is indices[1] # False

False

In [9]:
id(indices[0])

2518463953072

In [12]:
id(indices[1]) # 2518463946976
indices[1]==indices[0] # True

False

In [13]:
3^500000000^500000000

3

In [6]:
0 % 2

0

In [7]:
3//2

1

In [32]:
-2 % 5

3

In [9]:
2 // 3

0

In [ ]:
def euclidean(e, phi):


In [51]:
print(euclidean(2, 5))

0


In [34]:
message ="The right to remain perplexity"
def to_int(str):
    return int.from_bytes(str.encode(), byteorder='big')
to_int(message)

AttributeError: 'function' object has no attribute 'from_bytes'

In [35]:
def euclidean(e, phi):
    # e * d mod phi = 1
    # phi_n = p_n * e_n + phi_{n+1}
    # e_n = q_n * phi_n + e_{n+1}
    # d, k = coefficients of e in e_n phi_n w.r.t. e, phi
    d = 1
    k = 0
    phi0 = phi
    try:
        while 1:
            if e == 1:
                return d % phi0
            elif e == 0:
                return k % phi0
            else:
                p = phi // e
                phi %= e
                q = e // phi
                e %= phi
                k = k - p * d
                d = d - q * k
    except ZeroDivisionError:
        print("e, phi are not coprime")

In [37]:
euclidean(17,60*52)

2753

In [18]:
print(hash(11122))

11122


In [19]:
6666^555

6177

In [10]:
import os
role = "user"
os.environ["TASKS_FOLDER"] = r"C:\Users\liuSu\iCloudDrive\iCloud~md~obsidian\Note\Function"
os.environ["USER_NAME"] = "采薇"
os.environ["ASSISTANT_NAME"] = "山海"
tasks_folder = os.environ.get("TASKS_FOLDER")
user_name = os.environ.get("USER_NAME")
assistant_name = os.environ.get("ASSISTANT_NAME")
def get_tasks(role:str):
    """
    Get the list of tasks for the user or assistant.
    """
    path = os.path.join(tasks_folder, globals()[role+"_name"] + ".md")
    with open(path, "r", encoding="utf-8") as file:
        return file.read() 
get_tasks("user")

'- [ ] 《怪癖心理学》🔼 \n- [ ] 周六看无人机表演🔼 \n- [ ] 重拾初心\n- [/] 了解组合数学 🔼\n- [ ] 联系 [李才恒](https://math.sustech.edu.cn/c/licaiheng)老师，可以告诉他我的绩点 ⏫\n- [ ] 联系 [吴开亮](https://math.sustech.edu.cn/c/wukailiang) ?机器学习与数据科学 🔼 \n- [ ] oneshot 🔼 \n- [/] 广义张量~范畴，只要数学上没有新东西都可以用lean 🔼\n- [/] 学习数学建模，分享资料 🔼\n- [ ] 全国大学生“启真问智”人工智能模型&智能体大赛：赛事官网：https://kydh.zju.edu.cn 大赛报名通知链接：https://mp.weixin.qq.com/s/WWdaiiOvqd1QRA86z21EMQ ddl：2025年7月15日 🔼 \n- [ ] 起风了🔼 \n- [ ] 英国电话卡 #LATER ⏫ \n- [ ] AI agent 🔼 \n- [ ] 写志愿者报告 🔺 \n- [ ] 重建哲学社🔼 \n- [ ] 算法进阶🔼 \n'

In [ ]:
import pandas as pd

df= pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["New York", "Los Angeles", "Chicago"]
})

print(df.iloc[1:3, 1:3])
df[(df["age"] > 28) & (df["city"] == "New York")]  # 筛选年龄大于28且城市为New York的行

   age         city
1   30  Los Angeles
2   35      Chicago


TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
c = np.array([[1, 2], [3, 4], [5, 6]])
print(b[:, None])
print(A * b[:, None])

[[1]
 [2]
 [3]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [8]:
import numpy as np
np.cos(np.deg2rad(78.169))
a=np.array(["a",1])

In [ ]:
class cat:
    def __getitem__(self, key):
        # Return an array of ones with the same shape as key
        return np.ones_like(key)
mul = np.vectorize(lambda i, j: i * j, signature="(n),(n)->(n)")
result = mul(cat()[np.array([1,2,3])], np.array([1,2,3]))
print(result)

ValueError: inconsistent size for core dimension 'n': 3 vs 1

In [5]:
# 合并两个字典可以用 |（Python 3.9+）或 {**a, **b}
a ={}
a |= {1: 2}
print(a)

{1: 2}


In [5]:
not []

True